# This file is managed in https://github.com/happyprime/projects
name: Add new issues to Happy Prime project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    uses: happyprime/workflows/.github/workflows/issues.yml@trunk
    secrets: inherit
